[project]
name = "operating-system-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "customtkinter==0.3",
    "matplotlib>=3.10.3",
    "ruff>=0.11.11",
    "tk>=0.1.0",
]
